[env]
TERM = "xterm-256color"

[window]
opacity = 0.8
decorations = "None"
startup_mode = "Maximized"

[font]
size = 18
normal = { family = "FiraCode Nerd Font", style = "Retina" }
bold = { family = "FiraCode Nerd Font", style = "Medium" }

