[window]
opacity = 0.8
decorations = "None"
startup_mode = "Maximized"

[font]
size = 18
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }

