- hosts: localhost
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
  tasks:
    - include_tasks: tasks/tools-setup.yml
    - include_tasks: tasks/git-setup.yml
    - include_tasks: tasks/nvim-setup.yml
    - include_tasks: tasks/k9s-setup.yml
    - include_tasks: tasks/lazygit-setup.yml
    - include_tasks: tasks/kubectl-setup.yml
    - include_tasks: tasks/flux-setup.yml
    - include_tasks: tasks/helm-setup.yml

