- name: Install nodejs and npm
  become: true
  apt:
    name: ["nodejs", "npm"]
  tags:
    - install
    - node

- name: npmjs prefix
  shell: mkdir -p {{ lookup('env', 'HOME') }}/.local/.npm-global
  tags:
  - install
  - node

- name: add npmjs to path
  shell: PATH={{ lookup('env', 'HOME') }}/.local/.npm-global/bin:$PATH
  tags:
  - install
  - node

- name: npmjs global settings
  shell: npm config set prefix '{{ lookup('env', 'HOME') }}/.local/.npm-global'
  tags:
  - install
  - node

- name: Install N
  npm:
    name: n
    global: yes
  tags:
    - install
    - node

- name: Install correct version of Node
  become: true
  shell: |
    cd {{ lookup('env', 'HOME') }}/.local/.npm-global/bin
    ./n 16
  tags:
    - install
    - node

