- name: Get Packer
  ansible.builtin.git:
    repo: 'https://github.com/wbthomason/packer.nvim'
    dest: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
  tags:
    - install
    - neovim
- name: Download neovim
  shell: "curl -LO https://github.com/neovim/neovim/releases/download/stable/nvim-linux-x86_64.tar.gz"
  tags:
    - install
    - neovim
- name: Unpack neovim
  become: true
  shell: "tar -xvf nvim-linux-x86_64.tar.gz"
  tags:
    - install
    - neovim
- name: Install neovim
  become: true
  shell: "chmod +x nvim-linux-x86_64/bin/nvim && cp nvim-linux-x86_64/bin/nvim /usr/local/bin"
  tags:
    - install
    - neovim
- name: Clean
  become: true
  shell: "rm -rf nvim-linux-x86_64*"
  tags:
    - install
    - neovim
- name: Configure
  ansible.builtin.git:
    repo: 'https://github.com/jaxwood/nvim'
    dest: "{{ lookup('env', 'HOME') }}/.config/nvim"
  tags:
    - install
    - neovim
