- name: Install rtx
  become: true
  shell: |
    RTX_VERSION=$(curl -s "https://api.github.com/repos/jdxcode/rtx/releases/latest" | grep -Po '"tag_name": "v\K[^"]*')
    echo $RTX_VERSION
    curl -Lo rtx "https://github.com/jdxcode/rtx/releases/latest/download/rtx-v${RTX_VERSION}-linux-x64"
    chmod +x rtx
    mv rtx /usr/local/bin
  tags:
    - install
    - rtx
- name: Activate rtx
  become: true
  shell: |
    rtx activate zsh >> .zshrc
  tags:
    - install
    - rtx

